# -*- coding: utf-8 -*-
"""openaqFeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mirPDARRCmFX0gv23aKXqLgH7-aWGsFB
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Datasets/Level 2 OpenAQ Air Quality/openAQCleaned.csv')
df.head()

# Additional columns: weekday, is weekend and season
df['last updated'] = pd.to_datetime(df['last updated'], errors='coerce')
df['weekday'] = df['last updated'].dt.weekday

df['is weekend'] = df.weekday.isin([5, 6])

def monthToSeason(month: int) -> str:
  if month in [12, 1, 2]:
    return 'winter'
  elif month in [3, 4, 5]:
    return 'spring'
  elif month in [6, 7, 8]:
    return 'summer'
  else:
    return 'autumn'

df['season'] = df['month'].apply(monthToSeason)

# Dropping last updated column
df = df.drop(columns="last updated")

# Value lat. and value long --> to let the ML model capture potential
# relationships between pollutant levels and location
df['val lat'] = df['value'] * df['latitude']
df['val lon'] = df['value'] * df['longitude']

df.head()

# saving the file
df.to_csv('/content/drive/MyDrive/Datasets/Level 2 OpenAQ Air Quality/openAQFeatureEngineered.csv', index=False)