data:
  raw_data_path: "Telco-Customer-Churn/customer-churn/data/raw/telcoCustomerChurn.csv"
  processed_data_path: "Telco-Customer-Churn/customer-churn/data/processed/telcoCustomerChurnClean.csv"

features:
  target: "Churn"
  numerical: ["Tenure", "MonthlyCharges", "TotalCharges"]
  categorical: ["Gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService",
                "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup",
                "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies",
                "Contract", "PaperlessBilling", "PaymentMethod"]

model:
  type: "RandomForestClassifier"
  random_state: 42
  n_estimators: 100
  max_depth: None
  min_samples_split: 2
  cv_folds: 5
  scoring: "roc_auc"

training:
  test_size: 0.2
  stratify: true
