# -*- coding: utf-8 -*-
"""amesHousingFeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169UDuFZqKjf1Ohb4ExHZ2yuRx7_l2Lhs
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Datasets/Ames Housing Level 2/amesHousingCleaned.csv',
                 keep_default_na=False, na_values=[])
df.head()

"""### Creating new features"""

# property age
df['House Age'] = df['Yr Sold'] - df['Year Built']

# age since last remodel
df['Remod Age'] = df['Yr Sold'] - df['Year Remod/Add']

# total bathrooms
df['Total Bathrooms'] = df['Full Bath'] + 0.5 * df['Half Bath'] + df['Bsmt Full Bath'] + 0.5 * df['Bsmt Half Bath']

# capturing total outdoor living space
df['Total Porch SF'] = df['Open Porch SF'] + df['Enclosed Porch'] + df['3Ssn Porch'] + df['Screen Porch'] + df['Wood Deck SF']

# if the house has a pool
df['Has Pool'] = (df['Pool Area'] > 0).astype(int)

# fireplaces
df['Has Fireplace'] = (df['Fireplaces'] > 0).astype(int)

# garage presence
df['Has Garage'] = (df['Garage Area'] > 0).astype(int)

# interaction features that can improve predictive power (useful for tree-based models or linear models)
df['Overall Qual Gr Liv'] = df['Overall Qual'] * df['Gr Liv Area']
df['Total Rooms Gr Liv'] = df['TotRms AbvGrd'] * df['Gr Liv Area']

# temporal features
df['Built Decade'] = (df['Year Built'] // 10) * 10

# final dataset to work with
df.head()

# moving 'target' variable to the end
df = df[[col for col in df.columns if col != 'SalePrice'] + ['SalePrice']]

# result
df.head()

# saving the file
df.to_csv('/content/drive/MyDrive/Datasets/Ames Housing Level 2/amesHousingFeatureEngineering.csv', index=False)