# -*- coding: utf-8 -*-
"""onlineRetailFeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121oyIKjkFHidP0ueaDiVti5YWH6SQaBu
"""

import pandas as pd
import datetime as dt

df = pd.read_csv('/content/drive/MyDrive/Datasets/Level 2 Online Retail/cleanedDataset.csv')
df.head()

# creating TotalPrice column
df['TotalPrice'] = df['Quantity'] * df['Price']

# recency, frequency and monetary for each customer
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
snapshotDate = df['InvoiceDate'].max() + pd.Timedelta(days=1) # often max InvoiceDate + 1 day

rfm = df.groupby('Customer ID').agg(
    {
        'InvoiceDate': lambda x: (snapshotDate - x.max()).days,
        'Invoice': 'nunique',
        'TotalPrice': 'sum'
    }
).reset_index()
rfm.columns = ['Customer ID', 'Recency', 'Frequency', 'Monetary']
rfm.head()

# features per Description
productFeatures = df.groupby('Description').agg(
    {
        'Quantity': 'sum',
        'Invoice': 'nunique',
        'TotalPrice': 'sum',
    }
).reset_index()
productFeatures.columns = ['Description', 'Total Quantity Sold', 'Unique Invoices', 'Total Revenue']
productFeatures.head()

# time-based features
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Week'] = df['InvoiceDate'].dt.isocalendar().week
df['Day Of Week'] = df['InvoiceDate'].dt.day_of_week

df.head()

# monthly revenue
monthlyRevenue = df.groupby(['Year', 'Month'])['TotalPrice'].sum().reset_index()
monthlyRevenue.columns = ['Year', 'Month', 'Total Revenue']
monthlyRevenue.head(10)

# saving new files
rfm.to_csv('/content/drive/MyDrive/Datasets/Level 2 Online Retail/customersRfm.csv', index=False)
productFeatures.to_csv('/content/drive/MyDrive/Datasets/Level 2 Online Retail/productFeatures.csv', index=False)
monthlyRevenue.to_csv('/content/drive/MyDrive/Datasets/Level 2 Online Retail/monthlyRevenue.csv', index=False)