# -*- coding: utf-8 -*-
"""onlineRetailClean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgDKGNu0WwNsH7KaUEdBmRlxDjYfRHaJ
"""

import pandas as pd
import numpy as np

df = pd.read_excel('/content/drive/MyDrive/Datasets/Level 2 Online Retail/online_retail_II.xlsx')
df.head()

df.info()

df.size

# checking null values
df.isna().sum()

# stats
df.describe(include=['float64', 'int64'])

df['Invoice'] = df['Invoice'].astype(str)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# removing cancelled orders
df = df[~df['Invoice'].str.startswith('C')]

# filling na values with "unknown"
df.Description = df.Description.str.strip().fillna('Unknown')

# changing data type of StockCode
df.StockCode = df.StockCode.astype(str).str.strip()

# remove invalid quantities and prices
df = df[df.Quantity > 0]
df = df[df.Price > 0]

# drop missing customer IDs
df = df.dropna(subset=['Customer ID'])

# check the size after these changes
df.size

# saving the new file
df.to_csv('/content/drive/MyDrive/Datasets/Level 2 Online Retail/cleanedDataset.csv', index=False)