# -*- coding: utf-8 -*-
"""telcoFeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181abknUgeji5jg2BtpEdhlFQ8xN1ITXa
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

path = '/content/drive/MyDrive/Datasets/CSV and Excel files/telcoCustomerChurnClean.csv'
df = pd.read_csv(path)
df.head()

# tenure group customers
tenureBins = [0, 12, 24, 48, 72]
tenureLabels = ['0-12', '12-24', '24-48', '48-72']
df['Tenure Group'] = pd.cut(df['Tenure'], bins=tenureBins, labels=tenureLabels)

# "new customer" column
df['New Customer'] = (df.Tenure < 6).astype(int)

# counting how many services a customer has subscribed to
services = ['PhoneService', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']
df['Total Services'] = df[services].apply(lambda x: sum(x != "No"), axis=1)

# flag month-to-month customers
df['Month-To-Month'] = (df.Contract == 'Month-to-month').astype(int)

# group payment methods into automatic and manual
df['Auto Payment'] = df.PaymentMethod.str.contains('automatic').astype(int)

# average charge per tenure month
df["Avg. Monthly"] = df['TotalCharges'] / (df['Tenure'] + 1) # to avoid division by 0

# high spender category
threshold = df['MonthlyCharges'].quantile(0.9)
df['High Spender'] = (df['MonthlyCharges'] > threshold).astype(int)

df.to_csv('/content/drive/MyDrive/Datasets/CSV and Excel files/telcoFeatureEngineering.csv')