# -*- coding: utf-8 -*-
"""telcoCustomerChurnPreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aAjLCi2tC5vtGdHzixh8T9T8RT-ldUC
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

path = '/content/drive/MyDrive/Datasets/CSV and Excel files/WA_Fn-UseC_-Telco-Customer-Churn.csv'
df = pd.read_csv(path)
df.head()

# check column types
df.info()

# check missing values -> no missing values
df.isna().sum()

# changing data type of Total Charges to numeric
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.TotalCharges.dtype

# dropping customerId because we don't need it
df.drop('customerID', axis=1, inplace=True, errors='raise')

# changing column names
df.rename(columns={'gender': 'Gender', 'tenure': 'Tenure'}, inplace=True)

# variables for models
X = df.drop('Churn', axis=1, inplace=False)
y = df['Churn']

# saving the file
df.to_csv('/content/drive/MyDrive/Datasets/CSV and Excel files/telcoCustomerChurnClean.csv', index=False)