# ===============================
# 🛒 Online Retail Project Config
# ===============================

project:
  name: "Online Retail Analysis"
  author: "Arckimede"
  description: "EDA and customer segmentation using the UK Online Retail dataset."

paths:
  raw_data: "Real-World-Data-Science/OnlineRetail/data/raw/OnlineRetail.xlsx"
  cleaned_data: "Real-World-Data-Science/OnlineRetail/data/processed/online_retail_cleaned.csv"
  models: "Real-World-Data-Science/OnlineRetail/models/"
  notebooks: "Real-World-Data-Science/OnlineRetail/notebooks/"

data:
  date_column: "InvoiceDate"
  customer_id_column: "CustomerID"
  quantity_column: "Quantity"
  price_column: "UnitPrice"

preprocessing:
  remove_negative_quantities: true
  drop_missing_customers: true
