project:
  name: "Online Retail Analysis"
  author: "Arckimede"
  description: "EDA and customer segmentation using the UK Online Retail dataset."

paths:
  raw_data: "OnlineRetail/data/raw/OnlineRetail.xlsx"
  cleaned_data: "OnlineRetail/data/processed/online_retail_cleaned.csv"
  models: "OnlineRetail/models/"
  notebooks: "OnlineRetail/notebooks/"

data:
  date_column: "InvoiceDate"
  customer_id_column: "CustomerID"
  quantity_column: "Quantity"
  price_column: "UnitPrice"

preprocessing:
  remove_negative_quantities: true
  drop_missing_customers: true
